# Generated by Django 4.2.11 on 2024-12-03 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workoutApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='secondary_muscles',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
